VARGASERP/VARGASERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
        
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

VARGASERP/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login_user", views.login_user, name="login"),
    path("logout_user", views.logout_user, name="logout"),
    path("register_user", views.register_user, name="register"),
]

VARGASERP/main/urls.py
from django.urls import path
from . import views
from .controller import controller_egresos

urlpatterns = [
    path("", views.index, name="index"),

    path("egresos/", controller_egresos.egresos, name="egresos"),
    path("agregar-egreso/", controller_egresos.agregar_egresos,
         name="agregar_egresos"),
    path("validar-egreso/", controller_egresos.validar_egresos,
         name="validar_egresos"),
    path("editar-egreso/<id>", controller_egresos.editar_egreso, name="editar_egreso"),
    path("validar-edicion-egreso/<id>", controller_egresos.validar_edicion_egresos,
         name="validar_edicion_egresos"),
    path("eliminar-egreso/<id>", controller_egresos.eliminar_egresos,
         name="eliminar_egresos"),
]

VARGASERP/accounts/models.py
from django.db import models

# Create your models here.

VARGASERP/main/models.py
from django.db import models

# Create your models here.
class Proveedor(models.Model):
    codigo = models.CharField(max_length=250)
    ruc = models.CharField(max_length=250)
    nombre = models.CharField(max_length=250)
    contacto = models.CharField(max_length=250)
    observaciones = models.CharField(max_length=250)

class Stock(models.Model):
    id_proveedor = models.IntegerField
    marca = models.CharField(max_length=250)
    unidades_inicial = models.IntegerField
    unidades_disponible = models.IntegerField
    fecha_ingreso = models.DateField
    costo_unitario = models.FloatField
    costo_total = models.FloatField
    estado = models.CharField(max_length=250)
    encargado = models.CharField(max_length=250)

class Venta(models.Model):
    id_vale = models.IntegerField
    id_stock = models.IntegerField
    id_cliente = models.IntegerField
    nombre_cliente = models.CharField(max_length=250)
    dni_cliente = models.CharField(max_length=250)
    pago_parcial = models.FloatField
    deuda = models.FloatField
    precio_venta = models.FloatField
    observaciones = models.CharField(max_length=250)
    marca = models.CharField(max_length=250)
    unidades = models.IntegerField
    pago_rotal = models.FloatField
    fecha = models.DateField
    encargado = models.CharField(max_length=250)

class Egresos(models.Model):
    categoria = models.CharField(max_length=250)
    descripcion = models.CharField(max_length=250)
    costos= models.CharField(max_length=250)

class Vale(models.Model):
    id_cliente = models.IntegerField
    valor = models.FloatField
    unidades = models.IntegerField
    id_venta = models.IntegerField

class Cliente(models.Model):
    nombre = models.CharField(max_length=250)
    contacto = models.CharField(max_length=250)
    dni = models.CharField(max_length=8)
    observacion = models.CharField(max_length=250)

VARGASERP/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    CHOICES=[('vendedor','Vendedor'), ('admin','Admin')]
    group = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Correo'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'group']

VARGASERP/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import Group, User

from .forms import CreateUserForm

from django.contrib.auth.decorators import login_required
from .decorators import allowed_users

# Create your views here.

INDEX = '/'

def login_user(request):
    if request.user.is_authenticated:
        return redirect(INDEX)
    else:
        if request.method == 'POST':
            user = request.POST['user']
            password = request.POST['password']
            user = authenticate(request, username=user, password=password)
            if user is not None:
                login(request, user)
                return redirect(INDEX)
            else:
                messages.add_message(request,
                    messages.ERROR, 
                    'Contraseña o usuario incorrectos, intente nuevamente.'
                )
                return redirect('login')
        else:
            return render(request, 'auth/login.html', {})

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin', 'vendedor'])
def register_user(request):
    form = CreateUserForm(request.POST)
    if form.is_valid():
        user = form.save()
        username = form.cleaned_data['username']
        group = form.cleaned_data['group']
        if request.user.groups.filter(name='admin'):
            add_group = Group.objects.get(name=group)
        else:
            add_group = Group.objects.get(name='vendedor')
        user.groups.add(add_group)

        messages.add_message(request,
            messages.SUCCESS, 
            f'El {add_group} {username} fue creado correctamente.'
        )
        return redirect('login')

    else:
        form = CreateUserForm()

    context = {'form': form }
    return render(request, 'auth/register.html', context)

@login_required(login_url='login')
def logout_user(request):
    logout(request)
    messages.add_message(request,
        messages.WARNING, 
        'Se a cerrado sesión.'
    )
    return redirect('login')

VARGASERP/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users

# Create your views here.
# "ubicacion" y "desc" son propiedades que se muestran como info adicional en la página


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin', 'vendedor'])
def index(request):
    context = {
        "ubicacion": "Inicio"
    }
    return render(request, 'index.html', context)

VARGASERP/accounts/templates/authentication/login.html
{% extends "main/base_accounts.html" %}
{% load static %}

{% block title %} Login {% endblock %}
{% block style %} {% static 'css/accounts.css' %} {% endblock %}

{% block content %}
<section>
    <h1>login</h1>
    {% include "main/snippets/message.html" %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form_content">
            <label for="user">User</label>
            <input type="text" name="user" id="user">

            <label for="password">Password</label>
            <input type="password" name="password" id="password">

            <input type="submit" value="Ingresar">
        </div>
    </form>

</section>
{% endblock %}

VARGASERP/accounts/templates/authentication/register.html
{% extends "main/base_accounts.html" %}
{% load static %}

{% block title %} Registrar {% endblock %}
{% block style %} {% static 'css/accounts.css' %} {% endblock %}

{% block content %}
<section>
    <h1>registro usuario</h1>
    {% include "main/snippets/message.html" %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form_content">
            {% for field in form %}
            {{field.label}}
            {{ field }}
            {% endfor %}

            <input type="submit" value="Registrar">
            <a href="{% url 'main:index' %}">Volver a la pagina principal</a>
        </div>
    </form>

</section>
{% endblock %}

VARGASERP/main/templates/egresos/agregar_egreso.html
{% extends "main/base.html" %}
{% load static %}
{% load has_group %}

{% block title %} Registrar Egreso {% endblock %}
{% block style %} {% static 'css/dashboard.css' %} {% endblock %}
{% block dashboard_title %}Registrar Egreso{% endblock %}
{% block content %}
<form action="/validar-egreso/" method="post">
    {% csrf_token %}
    <label for="txtCategoria">Categoria</label>
    <input type="text" id="txtCategoria" name="txtCategoria" required>

    <label for="txtDescripcion">Descripcion</label>
    <input type="text" id="txtDescripcion" name="txtDescripcion" required>

    <label for="txtCostos">Costo</label>
    <input type="number" id="txtCostos" name="txtCostos" required>

    <button type="submit">Agregar</button>
</form>
{% endblock %}

VARGASERP/main/templates/egresos/editar_egreso.html
{% extends "main/base.html" %}
{% load static %}
{% load has_group %}

{% block title %} Editar Egreso {% endblock %}
{% block style %} {% static 'css/dashboard.css' %} {% endblock %}
{% block dashboard_title %}Editar Egreso{% endblock %}
{% block content %}
<form action="/validar-edicion-egreso/{{egreso.id}}" method="post">
    <h1>AGREGAR EGRESO</h1>

    {% csrf_token %}

    <label for="txtCategoria">Categoria</label>
    <input type="text" id="txtCategoria" name="txtCategoria" value="{{egreso.categoria}}" required>

    <label for="txtDescripcion">Descripcion</label>
    <input type="text" id="txtDescripcion" name="txtDescripcion" value="{{egreso.descripcion}}" required>

    <label for="txtCostos">Costo</label>
    <input type="text" id="txtCostos" name="txtCostos" value="{{egreso.costos}}" required>

    <button type="submit">Actualizar</button>
</form>
{% endblock %}

VARGASERP/main/templates/egresos/index.html
{% extends "main/base.html" %}
{% load static %}
{% load has_group %}

{% block title %} Dashboard Egresos{% endblock %}
{% block style %} {% static 'css/dashboard.css' %} {% endblock %}
{% block dashboard_title %}Egresos{% endblock %}
{% block content %}
<a href="/agregar-egreso">Agregar egreso</a>
<table>
    <thead>
        <th id="">Categoria</th>
        <th id="">Descripcion</th>
        <th id="">Costos</th>
        <th id="" colspan="2">Opciones</th>
    </thead>
    <tbody>
        {% for egreso in egresos %}
        <tr>
            <td>{{egreso.categoria}}</td>
            <td>{{egreso.descripcion}}</td>
            <td>{{egreso.costos}}</td>
            <td><a href="/editar-egreso/{{egreso.id}}">Editar</a></td>
            <td><a href="/eliminar-egreso/{{egreso.id}}">Eliminar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

VARGASERP/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="{% static 'image/fire.ico' %}" />

  <title>{% block title %} base {% endblock %}</title>

  <link rel="stylesheet" href="{% block style %} {% endblock %}" />
</head>

<body>
  <!-- {% include "main/snippets/header.html" %} -->
  <main class="main">
    {% include "main/snippets/sidebar.html" %}
    <div class="main__content">
      <h1 class="main__title">{% block dashboard_title %}Dashboard{% endblock %}</h1>
      {% include "main/snippets/message.html" %}

      {% block content %} {% endblock %}
    </div>
  </main>
  <!-- {% include "main/snippets/footer.html" %} -->
</body>

</html>

VARGASERP/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% load has_group %}

{% block title %} Dashboard Homepage{% endblock %}
{% block style %} {% static 'css/dashboard.css' %} {% endblock %}

{% block dashboard_title %}Dashboard{% endblock %}
{% block content %}
<img src="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.infocaptor.com%2Fimg%2Fbeautiful_dashboard_metrics_kpi_metalic.png&f=1&nofb=1"
    alt="demo" style="height: 100vh;">
{% endblock %}

VARGASERP/templates/base_accounts.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'image/fire.ico' %}" />

    <title>{% block title %} base {% endblock %}</title>

    <link rel="stylesheet" href="{% block style %} {% endblock %}" />
</head>

<body>
    {% block content %} {% endblock%}
</body>

</html>

VARGASERP/templates/dashboard/base_forms.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Base Forms {% endblock %}</title>
    <link rel="icon" href="{% static 'image/fire.ico' %}" />

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'library/adminlte/plugins/fontawesome-free/css/all.min.css' %}" />

    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'library/adminlte/css/adminlte.min.css' %}" />
</head>

<body class="sidebar-mini dark-mode">
    <div class="wrapper">
        <!-- Navbar -->
        {% include 'snippets/navbar.html' %}
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        {% include 'snippets/sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            {% include 'snippets/content-header.html'%}

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    {% block content %} {% endblock %}
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        {% include 'snippets/footer.html'%}

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'library/adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'library/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'library/adminlte/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'library/adminlte/js/demo.js' %}"></script>
</body>

</html>

VARGASERP/templates/dashboard/base_table.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>{% block title %} {{ ubicacion }} {% endblock %}</title>
	<link rel="icon" href="{% static 'image/fire.ico' %}" />

	<!-- Google Font: Source Sans Pro -->
	<link rel="icon" href="{% static 'image/fire.ico' %}" />
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{% static 'library/adminlte/plugins/fontawesome-free/css/all.min.css' %}" />
	<!-- DataTables -->
	<link rel="stylesheet"
		href="{% static 'library/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}" />
	<link rel="stylesheet"
		href="{% static 'library/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}" />
	<link rel="stylesheet"
		href="{% static 'library/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}" />
	<!-- Theme style -->
	<link rel="stylesheet" href="{% static 'library/adminlte/css/adminlte.min.css' %}" />
</head>

<body class="sidebar-mini layout-fixed dark-mode">
	<div class="wrapper">
		<!-- Navbar -->
		{% include 'snippets/navbar.html'%}

		<!-- Main Sidebar Container -->
		{% include 'snippets/sidebar.html'%}

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			{% include 'snippets/content-header.html'%}

			<!-- Main content -->
			<section class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-12">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">{{ desc }}</h3>
									<a class="btn btn-app bg-info float-right" href="{% block addhref %}{% endblock %}">
										<i class="fas fa-plus"></i> Agregar {{ ubicacion }}
									</a>
								</div>
								<!-- /.card-header -->
								<div class="card-body">
									{% block table %}{% endblock %}
								</div>
								<!-- /.card-body -->
							</div>
							<!-- /.card -->
						</div>
						<!-- /.col -->
					</div>
					<!-- /.row -->
				</div>
				<!-- /.container-fluid -->
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		{% include 'snippets/footer.html'%}

		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Control sidebar content goes here -->
		</aside>
		<!-- /.control-sidebar -->
	</div>
	<!-- ./wrapper -->

	<!-- jQuery -->
	<script src="{% static 'library/adminlte/plugins/jquery/jquery.min.js' %}"></script>
	<!-- Bootstrap 4 -->
	<script src="{% static 'library/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<!-- DataTables  & Plugins -->
	<script src="{% static 'library/adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
	<script
		src="{% static 'library/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script
		src="{% static 'library/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/jszip/jszip.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/pdfmake/pdfmake.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/pdfmake/vfs_fonts.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
	<script src="{% static 'library/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
	<!-- AdminLTE App -->
	<script src="{% static 'library/adminlte/js/adminlte.min.js' %}"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="{% static 'library/adminlte/js/demo.js' %}"></script>
	<!-- Page specific script -->
	<script>
		$(function () {
			$("#example1")
				.DataTable({
					"language": {
						"sProcessing": "Procesando...",
						"sLengthMenu": "Mostrar _MENU_ registros",
						"sZeroRecords": "No se encontraron resultados",
						"sEmptyTable": "Ningún dato disponible en esta tabla",
						"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
						"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
						"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
						"sInfoPostFix": "",
						"sSearch": "Buscar:",
						"sUrl": "",
						"sInfoThousands": ",",
						"sLoadingRecords": "Cargando...",
						"oPaginate": {
							"sFirst": "Primero",
							"sLast": "Último",
							"sNext": "Siguiente",
							"sPrevious": "Anterior"
						},
						"oAria": {
							"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
							"sSortDescending": ": Activar para ordenar la columna de manera descendente"
						}
					},
					responsive: true,
					lengthChange: false,
					autoWidth: false,
					buttons: [
						"excel",
						"pdf",
						"print",
						"colvis",
					],
				})
				.buttons()
				.container()
				.appendTo("#example1_wrapper .col-md-6:eq(0)");
		});
	</script>
</body>

</html>

VARGASERP/templates/egresos/agregar_egreso.html
{% extends "dashboard/base_forms.html" %}
{% load static %}
{% load has_group %}

{% block title %} Registrar {{ ubicacion }} {% endblock %}
{% block content %}
<div class="card col-md-8">
    <div class="card-body">
        <form action="/validar-egreso/" method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label for="txtCategoria">Categoria</label>
                <select class="form-control form-control-lg" id="txtCategoria" name="txtCategoria" required>
                    <option>Personal</option>
                    <option>Combustible</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                </select>
            </div>

            <label for="txtCostos">Costo (Soles)</label>
            <input class="form-control form-control-lg" type="number" id="txtCostos" name="txtCostos" required>

            <label for="txtDescripcion">Descripcion</label>
            <textarea class="form-control" rows="3" id="txtDescripcion" name="txtDescripcion"
                placeholder="Opcional"></textarea>

            <div class="mt-4 bg-transparent">
                <a href="javascript:history.back()" class="btn btn-lg btn-outline-danger float-left">
                    <i class="fas fa-backward"></i> Volver
                </a>
                <button class="btn btn-lg btn-outline-success float-right" type="submit">
                    <i class="fas fa-save"></i> Guardar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

VARGASERP/templates/egresos/editar_egreso.html
{% extends "dashboard/base_forms.html" %}
{% load static %}
{% load has_group %}

{% block title %} Editar {{ ubicacion }} {% endblock %}
{% block content %}
<div class="card col-md-8">
    <div class="card-body">
        <form action="/validar-edicion-egreso/{{egreso.id}}" method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label for="txtCategoria">Categoria</label>
                <select class="form-control form-control-lg" id="txtCategoria" name="txtCategoria"
                    value="{{egreso.categoria}}" required>
                    <option>Personal</option>
                    <option>Combustible</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                </select>
            </div>

            <label for="txtCostos">Costo (Soles)</label>
            <input class="form-control form-control-lg" type="number" id="txtCostos" name="txtCostos"
                value="{{egreso.costos}}" required>

            <label for="txtDescripcion">Descripcion</label>
            <textarea class="form-control" rows="3" id="txtDescripcion" name="txtDescripcion" placeholder="Opcional"
                value="{{egreso.costos}}"></textarea>

            <div class="mt-4 bg-transparent">
                <a href="javascript:history.back()" class="btn btn-lg btn-outline-danger float-left">
                    <i class="fas fa-backward"></i> Volver
                </a>
                <button class="btn btn-lg btn-outline-success float-right" type="submit">
                    <i class="fas fa-save"></i> Guardar Cambios
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

VARGASERP/templates/egresos/index_egreso.html
{% extends "dashboard/base_table.html" %}
{% load static %}
{% load has_group %}

{% block addhref %}/agregar-egreso{% endblock %}
{% block table %}
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Categoria</th>
            <th>Descripcion</th>
            <th>Costos</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for item in registro %}
        <tr>
            <td>{{item.categoria}}</td>
            <td>{{item.descripcion}}</td>
            <td>{{item.costos}}</td>
            <td>
                <div class="btn-group">
                    <a type="button" class="btn btn-info" href="/editar-egreso/{{item.id}}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Editar
                    </a>
                    <a type="button" class="btn btn-danger" href="/eliminar-egreso/{{item.id}}">
                        <i class=" fas fa-trash">
                        </i>
                        Eliminar
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

VARGASERP/templates/index.html
{% extends "dashboard/base_dashboard.html" %}
{% block title %} Inicio Vargas | Dashboard{% endblock %}

VARGASERP/templates/snippets/content-header.html
<section class="content-header">
    <div class="container-fluid">
        {% include "snippets/message.html" %}
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ ubicacion }}</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="/">Inicio</a>
                    </li>
                    <li class="breadcrumb-item active">
                        {{ ubicacion }}
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</section>

VARGASERP/templates/snippets/footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        Var<b>gas</b> 0.1.18
    </div>
    <strong>&copy;
    </strong>
</footer>

VARGASERP/templates/snippets/message.html
{% if messages %}
<!-- <div class="col-md-3 w-auto"> -->
<div class="w-auto">
    {% for message in messages %}
    <div class="card card-{{ message.tags }}">
        <div class="card-header">
            <h3 class="card-title">Notificacion</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                </button>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            {{ message }}
        </div>
        <!-- /.card-body -->
    </div>
    {% endfor %}
    <!-- /.card -->
</div>
{% endif %}

VARGASERP/templates/snippets/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-light">
	<!-- Left navbar links -->
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a href="/" class="nav-link">Inicio</a>
		</li>
	</ul>

	<!-- Right navbar links -->
	<ul class="navbar-nav ml-auto">

		<!-- Notifications Dropdown Menu -->
		<li class="nav-item dropdown">
			<a class="nav-link" data-toggle="dropdown" href="#">
				<i class="far fa-bell"></i>
				<span class="badge badge-warning navbar-badge">15</span>
			</a>
			<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
				<span class="dropdown-item dropdown-header">15 Notifications</span>
				<div class="dropdown-divider"></div>
				<a href="#" class="dropdown-item">
					<i class="fas fa-envelope mr-2"></i> 4 new
					messages
					<span class="float-right text-muted text-sm">3 mins</span>
				</a>
				<div class="dropdown-divider"></div>
				<a href="#" class="dropdown-item">
					<i class="fas fa-users mr-2"></i> 8 friend
					requests
					<span class="float-right text-muted text-sm">12 hours</span>
				</a>
				<div class="dropdown-divider"></div>
				<a href="#" class="dropdown-item">
					<i class="fas fa-file mr-2"></i> 3 new reports
					<span class="float-right text-muted text-sm">2 days</span>
				</a>
				<div class="dropdown-divider"></div>
				<a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
			</div>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-widget="fullscreen" href="#" role="button">
				<i class="fas fa-expand-arrows-alt"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="{% url 'logout' %}" type="button" class="btn btn-block btn-outline-danger">Cerrar Sesion</a>
		</li>
	</ul>
</nav>